services:
  youges:
    container_name: youges
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "5655:5655"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          memory: 256M

networks:
  default:
    external: true
    name: swag-network
